/*
 * Copyright 2022 Ideas2IT Technologies. All rights reserved.
 * IDEAS2IT PROPRIETARY/CONFIDENTIAL.
 */
package com.ideas2it.fooddeliverymanagement.repository;

import com.ideas2it.fooddeliverymanagement.model.Category;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

/**
 * A repository for the Category  which extends JpaRepository to perform
 * CRUD operation for category.
 *
 * @author - Naganandhini
 * @version - 1.0
 * @since - 2022-12-15
 */
public interface CategoryRepository extends JpaRepository<Category,Integer> {

    /**
     * <p>
     * To generate the category code as per the count of the categories
     * </p>
     *
     * @return - a generated code with prefix as first three characters of name in upper case
     */
    @Query(value = "select count(id) from category" , nativeQuery = true)
    Long getCategoriesCount();

    /**
     * <p>
     * To override the delete query generated by the spring to do soft delete
     * the category for the given id.
     * </p>
     *
     * @param id - the category id for which to be soft deleted
     */
    @Modifying
    @Query("update Category set isDeleted = true where id = :id")
    void deleteById(@Param("id") int id);

    /**
     * <p>
     * To fetch the category for the given name. if the given category name
     * does not exist in the category table, it will return null.
     * </p>
     *
     * @param name - the category name for which the category will be returned
     * @return - the category
     */
    Category findByName(String name);
}
